# Generated by Django 4.0 on 2021-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=2, max_length=130),
            preserve_default=False,
        ),
    ]
